### ISSUE TITLE
AccessToken reported as created but the creation fails if more than 28 tokens already exist in Etcd

### ISSUE THREAD

**Issue by boriska70** [gaia-adm/security-token-service#6]
CreateToken API takes a long time (20+ sec), then correct response returned but no token created in Etcd. This happens when more than 28 tokens already exist in Etcd /accesstokens directory. Exception thrown in EtcdTokenStore.getAccessToken(EtcdTokenStore.java:123): 

```
java.io.IOException: io.netty.handler.codec.TooLongFrameException: Response entity too large: HttpObjectAggregator$AggregatedFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 100233, cap: 100233, components=37))
HTTP/1.1 200 OK
Content-Type: application/json
X-Etcd-Cluster-Id: 3345b3d007d8fa52
X-Etcd-Index: 1187565
X-Raft-Index: 1680647
X-Raft-Term: 16
Date: Wed, 16 Dec 2015 16:24:54 GMT
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:55)
...
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:42)
    at org.springframework.security.oauth2.provider.token.store.EtcdTokenStore.getAccessToken(EtcdTokenStore.java:123)
    at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:84)
```

**Comment by boriska70** [comment]
**Reason**: Etcd4j uses Netty and it is configured to accept responses up to 100KB by default.
Each entry in /accesstokens directory is about 3.5KB, so 3.5x28 = ~100KB.
**Solution**:
1. Provide customized EtcdNettyClient during EtcdClient creation and set a higher limit (5MB, for example). This customization is described on [Etcd4j Readme file](https://github.com/jurmous/etcd4j#custom-parameters-on-etcdnettyclient)
2. Handle exception correctly and return HTTP 500, if any problem occurred

Tested up to full capacity (1400 access tokens->5MB) successfully. There is a performance degradation when number of entities increase, measured ~ from 700 to 1400. **Attached** ([duration.xlsx](https://github.com/gaia-adm/security-token-service/files/65201/duration.xlsx) )please find the details (only total measurement done for flow as described in the graph title, most of the impact comes from createToken operation as it requires big response and running through the entire resultset). Looks acceptable, in any case. However we should avoid 'select all' style operations against Etcd, when possible.
